"""FSL submission packet — the artefact that actually leaves the police station.

Two renderings of the same content:
  * Markdown  — returned by the MCP tool / API and for review in Git;
  * PDF       — printable forwarding packet (reportlab, no network, no browser).

Sections: forwarding note & narrative → ACT NOW (field actions) → ranked
examination schedule → per-exhibit handling & caveats → exhibits held for stage
2 → gaps / follow-up → laboratory plan with measured baselines → method,
limitations and integrity block (engine version, knowledge-base hash, result
SHA-256, chain-of-custody ledger head) → signatures.

Deliberately NOT included: names of victims, witnesses or accused (BNS 2023
§72 protects the identity of sexual-offence victims; Pramaan never asks for
names at all).
"""

from __future__ import annotations

import io
import re
from pathlib import Path
from typing import Any

from .models import TIER_LABELS, TriageResult, TriagedItem

_FIELD_ACTIONS = {"COLLECT_NOW", "COLLECTION_WINDOW_PASSED", "DIGITAL_OVERWRITE", "PERISHABLE", "QUALITY_AT_RISK",
                  "COLD_CHAIN_REQUIRED", "TIME_CRITICAL_COLLECTION", "DIGITAL_VOLATILE", "SAFETY_UNLOAD_FIRST",
                  "MANDATED_EXAMINATION"}

METHOD_STATEMENT = (
    "Priorities were computed by a deterministic, rule-based engine from a versioned forensic knowledge base. "
    "For every exhibit the Evidentiary Priority Index (EPI, 0-100) combines probative value (crime-type relevance x "
    "individualizing potential x contextual linkage), urgency (estimated hours until evidential quality or the field "
    "collection window is lost) and irreplaceability, using weights set per crime type. No language model produces "
    "or alters any score, tier or schedule. Degradation half-lives are conservative planning heuristics, not measured "
    "constants, and must be calibrated by the receiving laboratory. The ranking is decision support for the "
    "Investigating Officer; the FSL may re-order examinations on scientific grounds, and every officer override is "
    "recorded in the chain-of-custody ledger."
)


def _flag_codes(item: TriagedItem) -> str:
    return ", ".join(f.code for f in item.flags if f.severity in ("critical", "high")) or "-"


def _exam_path(item: TriagedItem) -> str:
    return " -> ".join(s.name for s in item.exam_sequence) or "-"


def act_now(result: TriageResult) -> list[tuple[TriagedItem, Any]]:
    out = []
    for it in result.items:
        for f in it.flags:
            if f.severity == "critical" and f.code in _FIELD_ACTIONS:
                out.append((it, f))
    return out


# ------------------------------------------------------------------ markdown
def packet_markdown(result: TriageResult, ledger_head: dict[str, Any] | None = None) -> str:
    r = result
    c = r.counts
    L: list[str] = []
    L.append(f"# FSL Submission Packet — {r.case_ref}")
    L.append("")
    L.append(f"> Generated by **Pramaan** v{r.engine_version} · case `{r.case_id}` · {r.created_at:%d %b %Y %H:%M} UTC  ")
    L.append(f"> Knowledge base `{r.kb_hash[:16]}` · result SHA-256 `{r.result_sha256[:16]}` · LLM layer: `{r.llm_provider}`")
    L.append("")
    L.append("| Field | Value |")
    L.append("|---|---|")
    L.append(f"| Crime type | {r.crime_label} |")
    if r.title:
        L.append(f"| Title | {r.title} |")
    L.append(f"| Exhibits | {c.get('total', 0)} (P1 {c.get('P1', 0)} · P2 {c.get('P2', 0)} · P3 {c.get('P3', 0)} · P4/held {c.get('P4', 0)}) |")
    L.append(f"| First submission (stage 1) | {c.get('stage1', c.get('total', 0))} exhibits |")
    L.append(f"| Urgent-testing flags | {c.get('urgent', 0)} exhibits |")
    if r.custody_deadline:
        L.append(f"| Custody deadline (BNSS §187(3)) | {r.custody_deadline:%d %b %Y} — reports requested before this date |")
    L.append("")
    L.append("## 1. Forwarding note")
    L.append("")
    L.append(r.narrative)
    L.append("")

    actions = act_now(r)
    L.append("## 2. ACT NOW — field and preservation actions")
    L.append("")
    if actions:
        for it, f in actions:
            L.append(f"- **{it.label}** ({it.classification.type_name}) — `{f.code}`: {f.message}")
    else:
        L.append("- No critical field actions.")
    L.append("")

    L.append("## 3. Ranked examination schedule (stage 1)")
    L.append("")
    L.append("| # | Exhibit | Type | Tier | EPI | Examination sequence | Urgent flags |")
    L.append("|---|---|---|---|---|---|---|")
    for it in r.items:
        if it.stage != 1:
            continue
        desc = it.description.replace("|", "/")
        L.append(f"| {it.rank} | **{it.label}** — {desc[:70]} | {it.classification.type_name} | {it.tier} | "
                 f"{it.score.epi:.1f} | {_exam_path(it)} | {_flag_codes(it)} |")
    L.append("")
    L.append("Tiers: " + "; ".join(f"**{k}** {v}" for k, v in TIER_LABELS.items()) + ".")
    L.append("")

    L.append("## 4. Handling, caveats and corroboration (P1–P2)")
    L.append("")
    for it in r.items:
        if it.tier not in ("P1", "P2"):
            continue
        L.append(f"### {it.label} — {it.classification.type_name} ({it.tier}, EPI {it.score.epi:.1f})")
        L.append("")
        L.append(f"- **Why this priority:** {it.rationale}")
        L.append(f"- **Handling:** {it.handling}")
        L.append(f"- **What it does not prove:** {it.caveat}")
        if it.corroborate_with:
            L.append(f"- **Corroborate with:** {'; '.join(it.corroborate_with)}")
        for f in it.flags:
            if f.severity in ("critical", "high", "medium"):
                L.append(f"- `{f.code}` ({f.severity}): {f.message}")
        L.append("")

    held = [it for it in r.items if it.stage == 2]
    L.append("## 5. Exhibits held for stage 2")
    L.append("")
    if held:
        L.append("| Exhibit | Type | EPI | Reason |")
        L.append("|---|---|---|---|")
        for it in held:
            reason = next((f.message for f in it.flags if f.code == "STAGED_HOLD"), "Low priority for this crime type (P4).")
            L.append(f"| {it.label} | {it.classification.type_name} | {it.score.epi:.1f} | {reason.replace('|', '/')} |")
    else:
        L.append("None — all exhibits are in the first submission.")
    L.append("")

    L.append("## 6. Gaps and follow-up actions")
    L.append("")
    if r.gaps:
        for g in r.gaps:
            L.append(f"- **[{g.severity.upper()}] {g.message}** — {g.action}")
    else:
        L.append("- No gaps detected against the crime profile.")
    L.append("")

    s = r.schedule
    L.append("## 7. Laboratory plan")
    L.append("")
    L.append(s.summary)
    L.append("")
    L.append("| Policy | Value retained | Perishable value | Late | P1 mean (days) | Makespan (days) |")
    L.append("|---|---|---|---|---|---|")
    for name, res in [("Pramaan: " + s.recommended.policy, s.recommended)] + list(s.baselines.items()):
        pv = "-" if res.perishable_value_retained is None else f"{res.perishable_value_retained:.1%}"
        L.append(f"| {name} | {res.value_retained:.1%} | {pv} | {res.late_count} | "
                 f"{res.p1_mean_completion_days if res.p1_mean_completion_days is not None else '-'} | {res.makespan_days} |")
    L.append("")
    if s.recommended.divisions:
        L.append("| Division | Examiners | Bench hours | Busy (working days) |")
        L.append("|---|---|---|---|")
        for d in s.recommended.divisions:
            L.append(f"| {d.name} | {d.examiners} | {d.total_hours} | {d.working_days} |")
        L.append("")

    L.append("## 8. Method, limitations and integrity")
    L.append("")
    L.append(METHOD_STATEMENT)
    L.append("")
    if r.parse_warnings:
        L.append("**Parser warnings (review manually):**")
        for w in r.parse_warnings:
            L.append(f"- {w}")
        L.append("")
    L.append("| Integrity field | Value |")
    L.append("|---|---|")
    L.append(f"| Engine version | {r.engine_version} |")
    L.append(f"| Knowledge-base SHA-256 | `{r.kb_hash}` |")
    L.append(f"| Result SHA-256 | `{r.result_sha256}` |")
    if ledger_head:
        L.append(f"| Ledger head | seq {ledger_head.get('seq')} · `{ledger_head.get('hash')}` |")
    L.append("")
    L.append("---")
    L.append("Investigating Officer: ____________________   SHO: ____________________   "
             "Received at FSL (name/date/seal intact Y/N): ____________________")
    L.append("")
    return "\n".join(L)


# ----------------------------------------------------------------------- pdf
_FONT_CANDIDATES = [
    ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"),
    ("/usr/share/fonts/dejavu/DejaVuSans.ttf", "/usr/share/fonts/dejavu/DejaVuSans-Bold.ttf"),
    ("/Library/Fonts/Arial Unicode.ttf", "/Library/Fonts/Arial Unicode.ttf"),
    ("C:/Windows/Fonts/arial.ttf", "C:/Windows/Fonts/arialbd.ttf"),
]
_ASCII_MAP = {"≥": ">=", "≤": "<=", "→": "->", "↔": "<->", "−": "-", "·": "-", "…": "...", "✓": "Y", "×": "x"}


def _fonts() -> tuple[str, str, bool]:
    """Register a Unicode TTF if one exists; otherwise fall back to Helvetica (+ ASCII sanitising)."""
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont

    for regular, bold in _FONT_CANDIDATES:
        if Path(regular).is_file() and Path(bold).is_file():
            try:
                if "PramaanSans" not in pdfmetrics.getRegisteredFontNames():
                    pdfmetrics.registerFont(TTFont("PramaanSans", regular))
                    pdfmetrics.registerFont(TTFont("PramaanSans-Bold", bold))
                return "PramaanSans", "PramaanSans-Bold", True
            except Exception:  # pragma: no cover - corrupt font file
                continue
    return "Helvetica", "Helvetica-Bold", False


def _esc(text: str, unicode_ok: bool) -> str:
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    if not unicode_ok:
        for k, v in _ASCII_MAP.items():
            text = text.replace(k, v)
        text = text.encode("latin-1", "replace").decode("latin-1")
    return text


def packet_pdf(result: TriageResult, ledger_head: dict[str, Any] | None = None) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.enums import TA_LEFT
    from reportlab.lib.pagesizes import A4, landscape
    from reportlab.lib.styles import ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        KeepTogether, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle,
    )

    regular, bold, uni = _fonts()
    ink = colors.HexColor("#1d2330")
    muted = colors.HexColor("#5b6475")
    rule = colors.HexColor("#c9ced8")
    tier_col = {"P1": colors.HexColor("#b3261e"), "P2": colors.HexColor("#b86e00"),
                "P3": colors.HexColor("#1f6f78"), "P4": colors.HexColor("#6b7280")}

    base = ParagraphStyle("base", fontName=regular, fontSize=8.6, leading=11.2, textColor=ink, alignment=TA_LEFT)
    small = ParagraphStyle("small", parent=base, fontSize=7.4, leading=9.4, textColor=muted)
    cell = ParagraphStyle("cell", parent=base, fontSize=7.6, leading=9.6)
    cellb = ParagraphStyle("cellb", parent=cell, fontName=bold)
    h1 = ParagraphStyle("h1", parent=base, fontName=bold, fontSize=15, leading=19, spaceAfter=2)
    h2 = ParagraphStyle("h2", parent=base, fontName=bold, fontSize=10.5, leading=14, spaceBefore=9, spaceAfter=4)
    h3 = ParagraphStyle("h3", parent=base, fontName=bold, fontSize=9, leading=12, spaceBefore=5, spaceAfter=2)

    def P(text: str, style: ParagraphStyle = base) -> Paragraph:
        return Paragraph(_esc(text, uni), style)

    def table(rows: list[list[Any]], widths: list[float], header: bool = True, zebra: bool = True) -> Table:
        t = Table(rows, colWidths=widths, repeatRows=1 if header else 0)
        style = [
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LINEBELOW", (0, 0), (-1, -1), 0.25, rule),
            ("LEFTPADDING", (0, 0), (-1, -1), 3), ("RIGHTPADDING", (0, 0), (-1, -1), 3),
            ("TOPPADDING", (0, 0), (-1, -1), 2.5), ("BOTTOMPADDING", (0, 0), (-1, -1), 2.5),
        ]
        if header:
            style += [("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#e9ecf2")),
                      ("LINEBELOW", (0, 0), (-1, 0), 0.8, ink)]
        if zebra:
            for i in range(1 if header else 0, len(rows)):
                if i % 2 == 0:
                    style.append(("BACKGROUND", (0, i), (-1, i), colors.HexColor("#f7f8fa")))
        t.setStyle(TableStyle(style))
        return t

    r = result
    c = r.counts
    buf = io.BytesIO()
    page = landscape(A4)
    doc = SimpleDocTemplate(buf, pagesize=page, leftMargin=14 * mm, rightMargin=14 * mm, topMargin=14 * mm,
                            bottomMargin=14 * mm, title=f"FSL submission packet {r.case_id}", author="Pramaan",
                            subject=r.case_ref)
    W = page[0] - 28 * mm

    def on_page(canvas, doc_) -> None:  # footer with integrity data on every page
        canvas.saveState()
        canvas.setFont(regular, 6.8)
        canvas.setFillColor(muted)
        head = f" | ledger head {ledger_head['hash'][:16]}" if ledger_head else ""
        canvas.drawString(14 * mm, 8 * mm, _esc(
            f"Pramaan v{r.engine_version} | case {r.case_id} | KB {r.kb_hash[:16]} | result {r.result_sha256[:16]}{head}", uni
        ).replace("&amp;", "&"))
        canvas.drawRightString(page[0] - 14 * mm, 8 * mm, f"Page {doc_.page}")
        canvas.restoreState()

    story: list[Any] = []
    story.append(P("FSL SUBMISSION PACKET", small))
    story.append(P(r.case_ref, h1))
    meta = [
        [P("Crime type", cellb), P(r.crime_label, cell), P("Case ID", cellb), P(r.case_id, cell)],
        [P("Exhibits", cellb), P(f"{c.get('total', 0)} total - P1 {c.get('P1', 0)} / P2 {c.get('P2', 0)} / "
                                 f"P3 {c.get('P3', 0)} / P4 {c.get('P4', 0)}", cell),
         P("Generated (UTC)", cellb), P(f"{r.created_at:%d %b %Y %H:%M}", cell)],
        [P("First submission", cellb), P(f"{c.get('stage1', c.get('total', 0))} exhibits (stage 1)", cell),
         P("Custody deadline", cellb),
         P(f"{r.custody_deadline:%d %b %Y} (BNSS §187(3))" if r.custody_deadline else "Not applicable", cell)],
    ]
    if r.title:
        meta.insert(0, [P("Title", cellb), P(r.title, cell), P("LLM layer", cellb), P(r.llm_provider, cell)])
    story.append(table(meta, [W * 0.13, W * 0.37, W * 0.13, W * 0.37], header=False, zebra=False))
    story.append(P("1. Forwarding note", h2))
    story.append(P(r.narrative))

    story.append(P("2. ACT NOW - field and preservation actions", h2))
    actions = act_now(r)
    if actions:
        rows = [[P("Exhibit", cellb), P("Type", cellb), P("Action", cellb)]]
        for it, f in actions:
            rows.append([P(it.label, cellb), P(it.classification.type_name, cell), P(f"{f.code}: {f.message}", cell)])
        story.append(table(rows, [W * 0.10, W * 0.18, W * 0.72]))
    else:
        story.append(P("No critical field actions."))

    story.append(P("3. Ranked examination schedule (stage 1)", h2))
    rows = [[P(h, cellb) for h in ("#", "Exhibit", "Description", "Type", "Tier", "EPI", "Examination sequence", "Urgent flags")]]
    tier_rows = []
    for it in r.items:
        if it.stage != 1:
            continue
        rows.append([P(str(it.rank), cell), P(it.label, cellb), P(it.description[:110], cell),
                     P(it.classification.type_name, cell), P(it.tier, cellb), P(f"{it.score.epi:.1f}", cell),
                     P(_exam_path(it), cell), P(_flag_codes(it), cell)])
        tier_rows.append((len(rows) - 1, it.tier))
    t = table(rows, [W * 0.035, W * 0.065, W * 0.22, W * 0.12, W * 0.04, W * 0.04, W * 0.29, W * 0.19])
    t.setStyle(TableStyle([("TEXTCOLOR", (4, i), (4, i), tier_col[tier]) for i, tier in tier_rows]))
    story.append(t)
    story.append(P("Tiers: " + "; ".join(f"{k} {v}" for k, v in TIER_LABELS.items()) + ".", small))

    story.append(PageBreak())
    story.append(P("4. Handling, caveats and corroboration (P1-P2)", h2))
    for it in r.items:
        if it.tier not in ("P1", "P2"):
            continue
        block = [P(f"{it.label} - {it.classification.type_name} ({it.tier}, EPI {it.score.epi:.1f})", h3),
                 Paragraph(f"<b>Why:</b> {_esc(it.rationale, uni)}", base),
                 Paragraph(f"<b>Handling:</b> {_esc(it.handling, uni)}", base),
                 Paragraph(f"<b>Does not prove:</b> {_esc(it.caveat, uni)}", base)]
        if it.corroborate_with:
            block.append(Paragraph(f"<b>Corroborate with:</b> {_esc('; '.join(it.corroborate_with), uni)}", base))
        for f in it.flags:
            if f.severity in ("critical", "high", "medium"):
                block.append(Paragraph(f"<b>{_esc(f.code, uni)}</b> ({f.severity}): {_esc(f.message, uni)}", small))
        story.append(KeepTogether(block))

    held = [it for it in r.items if it.stage == 2]
    story.append(P("5. Exhibits held for stage 2", h2))
    if held:
        rows = [[P(h, cellb) for h in ("Exhibit", "Type", "EPI", "Reason")]]
        for it in held:
            reason = next((f.message for f in it.flags if f.code == "STAGED_HOLD"), "Low priority for this crime type (P4).")
            rows.append([P(it.label, cellb), P(it.classification.type_name, cell), P(f"{it.score.epi:.1f}", cell), P(reason, cell)])
        story.append(table(rows, [W * 0.09, W * 0.16, W * 0.05, W * 0.70]))
    else:
        story.append(P("None - all exhibits are in the first submission."))

    story.append(P("6. Gaps and follow-up actions", h2))
    if r.gaps:
        rows = [[P(h, cellb) for h in ("Severity", "Finding", "Action")]]
        for g in r.gaps:
            rows.append([P(g.severity.upper(), cellb), P(g.message, cell), P(g.action, cell)])
        story.append(table(rows, [W * 0.08, W * 0.46, W * 0.46]))
    else:
        story.append(P("No gaps detected against the crime profile."))

    s = r.schedule
    story.append(P("7. Laboratory plan", h2))
    story.append(P(s.summary))
    story.append(Spacer(1, 4))
    rows = [[P(h, cellb) for h in ("Policy", "Value retained", "Perishable value", "Late", "P1 mean (days)", "Makespan (days)")]]
    for name, res in [("Pramaan: " + s.recommended.policy, s.recommended)] + list(s.baselines.items()):
        rows.append([P(name, cellb if name.startswith("Pramaan") else cell), P(f"{res.value_retained:.1%}", cell),
                     P("-" if res.perishable_value_retained is None else f"{res.perishable_value_retained:.1%}", cell),
                     P(str(res.late_count), cell),
                     P("-" if res.p1_mean_completion_days is None else str(res.p1_mean_completion_days), cell),
                     P(str(res.makespan_days), cell)])
    story.append(table(rows, [W * 0.30, W * 0.14, W * 0.14, W * 0.10, W * 0.16, W * 0.16]))
    if s.recommended.divisions:
        story.append(Spacer(1, 4))
        rows = [[P(h, cellb) for h in ("Division", "Examiners", "Bench hours", "Busy (working days)")]]
        for d in s.recommended.divisions:
            rows.append([P(d.name, cell), P(str(d.examiners), cell), P(str(d.total_hours), cell), P(str(d.working_days), cell)])
        story.append(table(rows, [W * 0.40, W * 0.20, W * 0.20, W * 0.20]))

    story.append(P("8. Method, limitations and integrity", h2))
    story.append(P(METHOD_STATEMENT))
    for w in r.parse_warnings:
        story.append(P(f"Parser warning: {w}", small))
    rows = [[P("Engine version", cellb), P(r.engine_version, cell)],
            [P("Knowledge-base SHA-256", cellb), P(r.kb_hash, cell)],
            [P("Result SHA-256", cellb), P(r.result_sha256, cell)]]
    if ledger_head:
        rows.append([P("Chain-of-custody ledger head", cellb), P(f"seq {ledger_head.get('seq')} - {ledger_head.get('hash')}", cell)])
    story.append(table(rows, [W * 0.22, W * 0.78], header=False, zebra=False))
    story.append(Spacer(1, 16))
    story.append(table([[P("Investigating Officer (sign/date)", small), P("SHO (sign/date)", small),
                         P("Received at FSL - name / date / seals intact Y/N", small)],
                        [Spacer(1, 22), Spacer(1, 22), Spacer(1, 22)]],
                       [W / 3] * 3, header=False, zebra=False))

    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buf.getvalue()


def safe_filename(text: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]+", "_", text).strip("_")[:80] or "case"
